[build]
  Command = "npm run build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["graphql", "@prisma/client", "apollo-server-lambda", "ts-is-defined", "@opentelemetry/instrumentation" ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
