# Orb 'cypress-io/cypress@1.0.1' resolved to 'cypress-io/cypress@1.0.1'
version: 2
jobs:
  check:
    docker:
      - image:  circleci/node:11.15.0-stretch-browsers
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: web client - npm
          command: npm ci
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: web client - build
          command: npm run build
  build:
    docker:
      - image: cypress/base:10
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Set PR number
          command: |
            env | grep CIRCLE | sort
            echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
            source $BASH_ENV
            echo PR no.: $CIRCLE_PR_NUMBER
      - run:
          name: builds diagnosis
          command: |
            echo PR no.: $CIRCLE_PR_NUMBER
            source $BASH_ENV
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo " there is this PR number: $CIRCLE_PR_NUMBER"
            fi
            echo "Value of CIRCLE_PULL_REQUEST: ${CIRCLE_PULL_REQUEST} "
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              echo transformed to ${CIRCLE_PULL_REQUEST##*/}
              echo " there is this PR number: $CIRCLE_PR_NUMBER" ...
            fi
            env | grep CIRCLE | sort
            echo PR no.: $CIRCLE_PR_NUMBER
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "smoketest/package.json" }}
      - run:
          name: Npm CI
          command: |
            echo PR no.: $CIRCLE_PR_NUMBER
            echo $CIRCLE_PR_NUMBER
            if [ "X${CIRCLE_PR_NUMBER}" == "X" ]; then
              echo no CIRCLE_PR_NUMBER set, so skipping this step
            else
              cd smoketest ; npm ci
            fi
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "smoketest/package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: cypress verify
          command: |
            echo PR no.: $CIRCLE_PR_NUMBER
            export CYPRESS_baseUrl=https://deploy-preview-${CIRCLE_PR_NUMBER}--coolboard.netlify.com
            if [ "X${CYPRESS_baseUrl}" == "X" ]; then
              echo no CYPRESS_baseUrl set, so skipping this step
            else
              cd smoketest ; npx cypress verify
            fi
      - run:
          name: cypress cache path
          command: |
            echo PR no.: $CIRCLE_PR_NUMBER
            export CYPRESS_baseUrl=https://deploy-preview-${CIRCLE_PR_NUMBER}--coolboard.netlify.com
            if [ "X${CIRCLE_PR_NUMBER}" == "X" ]; then
              echo no $CIRCLE_PR_NUMBER set, so skipping this step
            else
              cd smoketest ; npx cypress cache path
            fi
      - run:
          name: run cypress
          command: |
            echo PR no.: $CIRCLE_PR_NUMBER
            export CYPRESS_baseUrl=https://deploy-preview-${CIRCLE_PR_NUMBER}--coolboard.netlify.com
            if [ "X${CIRCLE_PR_NUMBER}" == "X" ]; then
              echo no $CIRCLE_PR_NUMBER set, so skipping running tests
            else
              cd smoketest ; mkdir -p cypress/results ; npx cypress run --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            fi
      - store_test_results:
          path: smoketest/cypress/results
      - store_artifacts:
          path: /root/project/smoketest/cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: /root/project/smoketest/cypress/videos
          destination: videos

workflows:
  build:
    jobs:
      - check
  smoke:
    jobs:
      - build
  version: 2
