# Orb 'cypress-io/cypress@1.0.1' resolved to 'cypress-io/cypress@1.0.1'
version: 2
jobs:
  check:
    docker:
      - image:  circleci/node:11.9.0-stretch-browsers
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: web client - npm CI
          command: npm ci
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: web client - build
          command: npm run build
  build:
    docker:
      - image: cypress/base:10
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "smoketest/package.json" }}
      - run:
          name: Npm CI
          command: |
            if [ "X${CYPRESS_baseUrl}" == "X" ]; then
              echo no CYPRESS_baseUrl set, so skipping this step
            else
              cd smoketest ; npm ci
            fi
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "smoketest/package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: cypress verify
          command: |
            if [ "X${CYPRESS_baseUrl}" == "X" ]; then
              echo no CYPRESS_baseUrl set, so skipping this step
            else
              cd smoketest ; npx cypress verify
            fi
      - run:
          name: cypress cache path
          command: |
            if [ "X${CYPRESS_baseUrl}" == "X" ]; then
              echo no CYPRESS_baseUrl set, so skipping this step
            else
              cd smoketest ; npx cypress cache path
            fi
      - run:
          name: run cypress
          command: |
            if [ "X${CYPRESS_baseUrl}" == "X" ]; then
              echo no CYPRESS_baseUrl set, so skipping running tests
            else
              cd smoketest ; mkdir -p cypress/results ; npx cypress run --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            fi
      - store_test_results:
          path: smoketest/cypress/results
      - store_artifacts:
          path: /root/project/smoketest/cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: /root/project/smoketest/cypress/videos
          destination: videos

workflows:
  build:
    jobs:
      - check
  smoke:
    jobs:
      - build
  version: 2
