version: 2.1

parameters:
  gh-pr:
    type: string
    default: ""
  test-url:
    type: string
    default: ""
  deployed-sha:
    type: string
    default: ""
  VERCEL_URL:
    type: string
    default: ""

# have a filter to disable regular builds.
workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  install_and_cache:
    docker:
      - image:  cypress/base:20.5.0
    resource_class: lowsky/selfhosted
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-cy-{{ checksum "smoketest/yarn.lock" }}
      - run:
          name: smoketest - yarn install
          command: |
            cd smoketest
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - save_cache:
          key: cache-cy-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/.node_modules
            - smoketest/.yarn/install-state.gz
            - smoketest/.cache
            - ~/.cache/Cypress/
  build:
    docker:
      - image: cypress/base:20.5.0
    resource_class: lowsky/selfhosted
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Use parameters
          command: |
            echo parameters:
            echo gh-pr: "<< pipeline.parameters.gh-pr >>"
            echo test-url: << pipeline.parameters.test-url >>
            echo VERCEL_URL=<<pipeline.parameters.VERCEL_URL>>
            echo deployed-sha: <<pipeline.parameters.deployed-sha>>
      - run:
          name: build env and parameter diagnosis
          command: |
            env | grep CIRCLE | sort

            CIRCLE_PR_NUMBER=<< pipeline.parameters.gh-pr >>
            CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>
            VERCEL_URL=<< pipeline.parameters.VERCEL_URL >>

            env | grep CIRCLE | grep -v '\*\*\*' | sort

            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo " there is this PR number: $CIRCLE_PR_NUMBER"
            fi

            if [ "X${CIRCLE_PR_NUMBER}${CYPRESS_baseUrl}${EXPECTED_GIT_SHA}" == "X" ]; then
              echo there are NO parameters. done.
              circleci-agent step halt
            fi
      - run:
          name: more messages
          command: |
            cd smoketest

            VERCEL_URL=<< pipeline.parameters.VERCEL_URL >>
            CIRCLE_PR_NUMBER=<< pipeline.parameters.gh-pr >>
            CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>

            echo VERCEL_URL=$VERCEL_URL
            echo
            echo SUT:
            echo CYPRESS_baseUrl=$CYPRESS_baseUrl
            echo
            echo circle.ci - CIRCLE_SHA1=$CIRCLE_SHA1
            echo expected
            echo EXPECTED_GIT_SHA=$EXPECTED_GIT_SHA
            echo
            echo running GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1} check-deployed-version/check-deployed-version
            CYPRESS_baseUrl=$CYPRESS_baseUrl GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1} check-deployed-version/check-deployed-version

      - run:
          name: check git commit version
          command: |
            export CIRCLE_PR_NUMBER=<< pipeline.parameters.gh-pr >>
            export CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            export EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>
            export VERCEL_URL=<< pipeline.parameters.VERCEL_URL >>

            cd smoketest
            mkdir -p cypress/results

            CIRCLE_PR_NUMBER=<< pipeline.parameters.gh-pr >>
            CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>

            if [ "X${CIRCLE_PR_NUMBER}${CYPRESS_baseUrl}${EXPECTED_GIT_SHA}" == "X" ]; then
              echo there are NO parameters. done.
              exit 0
            fi

            GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1} npm run wait:valid-version ; CHECK_VERSION=$?

            echo CHECK VERSION result: $CHECK_VERSION

            if [  "$CHECK_VERSION" -eq "255"  ] ;  then
              echo "Version does not match with $EXPECTED_GIT_SHA"
              exit 23
            fi

      - restore_cache:
          keys:
            - cache-cy2-{{ checksum "smoketest/yarn.lock" }}
      - run:
          name: smoketest - yarn install
          command: |
            cd smoketest
            #PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
            #yarn cypress verify
            yarn cypress cache path
      - save_cache:
          key: cache-cy2-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/.node_modules
            - smoketest/.yarn/install-state.gz
            - smoketest/.cache
            - ~/.cache/Cypress/

      - run:
          name: run cypress
          command: |
            export CIRCLE_PR_NUMBER=<< pipeline.parameters.gh-pr >>
            export CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            export EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>
            export VERCEL_URL=<< pipeline.parameters.VERCEL_URL >>
            export CYPRESS_branch=${CIRCLE_BRANCH}

            cd smoketest
            mkdir -p cypress/results
            npx cypress info

            echo running CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record
            # CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record --key $CYPRESS_API_KEY --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            # without reporting to cypress.io
            CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
      - store_test_results:
          path: smoketest/cypress/results
      - store_artifacts:
          path: /root/project/smoketest/cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: /root/project/smoketest/cypress/videos
          destination: videos
