version: 2.1
orbs:
  pr-status: myoan/pr-status@0.0.1
  github-status: samsalisbury/github-status@0.0.1

parameters:
  test-url:
    type: string
    default: ''
  deployed-sha:
    type: string
    default: ''

# have a filter to disable regular builds.
workflows:
  all:
    jobs:
      - pr-pending
      - test:
          requires:
            - pr-pending
      - pr-success:
          requires:
              - test

executors:
  executor_with_curl:
    docker:
      - image: cimg/base:stable

jobs:
  pr-pending:
    executor: executor_with_curl
    environment:
      CIRCLE_BUILD_URL: ${CIRCLE_BUILD_URL}
    steps:
      - run:
          echo _debug_ CIRCLE_BUILD_URL=$CIRCLE_BUILD_URL
      - github-status/pending:
          description: pending
          context: cypress e2e test

  pr-success:
    executor: executor_with_curl
    environment:
      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
      CYPRESS_branch: ${CIRCLE_BRANCH}
    steps:
      - run:
          name: pre-check for params
          command: |
            if [  "x" == "x${CYPRESS_baseUrl}"  ] ;  then
              circleci step halt # does nothing
              circleci-agent step halt # does nothing

              echo "   No parameters -skipping build ..."
              exit 0
            fi

      - github-status/post_status:
          context: cypress e2e test
          description: success
          state: success

  install_and_cache:
    docker:
      - image: cypress/base:20.11.0
    resource_class: lowsky/selfhosted
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
      - run:
          name: smoketest - yarn install
          command: |
            cd smoketest
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - save_cache:
          key: cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/node_modules
  test:
    docker:
      - image: cypress/base:20.11.0
    resource_class: lowsky/selfhosted
    environment:
      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
      EXPECTED_GIT_SHA: << pipeline.parameters.deployed-sha >>
      CYPRESS_branch: ${CIRCLE_BRANCH}
    steps:
      - run:
          name: Show parameters
          command: |
            echo parameters / diagnosis:
            echo
            echo CYPRESS_baseUrl: $CYPRESS_baseUrl
            echo CYPRESS_branch: ${CIRCLE_BRANCH}
            ls -a /root/.cache
      - run:
          name: pre-check for params
          command: |
            if [  "x" == "x${CYPRESS_baseUrl}"  ] ;  then
              circleci step halt # does nothing
              circleci-agent step halt # does nothing
              echo "   No parameters -skipping build ..."
              exit 0
            fi

      - checkout
      - run:
          name: check matching of versions
          command: |
            cd smoketest

            echo export CYPRESS_baseUrl=$CYPRESS_baseUrl
            echo
            echo _DEBUG:  circle.ci -
            echo _DEBUG:    CIRCLE_SHA1=$CIRCLE_SHA1
            echo _DEBUG:
            echo _DEBUG:  expecting
            echo export EXPECTED_GIT_SHA=$EXPECTED_GIT_SHA
            echo export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}
            echo _DEBUG:
            echo _DEBUG:  running
            echo _DEBUG:     check-deployed-version/check-deployed-version

            export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}

            check-deployed-version/check-deployed-version || CHECK_VERSION=$?

            echo _DEBUG: check - result: $CHECK_VERSION

            if [  "x-$CHECK_VERSION" == "x-255"  ] ;  then
              echo "Version does not match with $EXPECTED_GIT_SHA"
              exit -1
            fi

      - restore_cache:
          keys:
            - cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}

      - run:
          name: smoketest - yarn install cypress
          command: |
            cd smoketest
            yarn install --immutable
            yarn cypress install
            # yarn cypress info
            # yarn cypress verify
      - save_cache:
          key: cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/node_modules

      - run:
          name: run cypress
          command: |
            cd smoketest
            mkdir -p cypress/results

            echo _DEBUG:  running without reporting to cypress.io:
            echo CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record --key $CYPRESS_API_KEY --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            echo CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            echo ...without reporting to cypress.io:

            CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true

      - store_test_results:
          path: smoketest/cypress/results
      - store_artifacts:
          path: /root/project/smoketest/cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: /root/project/smoketest/cypress/videos
          destination: videos
