version: 2.1
orbs:
  github-status: assurance-maladie-digital/github-status@1.3.0

parameters:
  test-url:
    type: string
    default: ''
  deployed-sha:
    type: string
    default: ''

# have a filter to disable regular builds.
workflows:
  all:
    jobs:
      - pr-pending
      - test:
          requires:
            - pr-pending
      - pr-success:
          requires:
            - test
      # LATER- report-failed-status-only-custom: requires: - test

executors:
  executor_with_curl:
    docker:
      - image: cimg/base:stable

jobs:
  pr-pending:
    executor: executor_with_curl
    environment:
      DEBUG: true
    steps:
      - run: echo "export TARGET_URL=$CIRCLE_BUILD_URL" >> $BASH_ENV
      - github-status/pending:
          description: pending
          context: e2e/cypress-test
  report-failed-status-only:
    executor: executor_with_curl
    steps:
      - run: exit 1
      - github-status/report_failed_only
  report-failed-status-only-custom:
    executor: executor_with_curl
    steps:
      - run: echo "export TARGET_URL=$CIRCLE_BUILD_URL" >> $BASH_ENV
      - run: exit 1
      - github-status/report_failed_only:
          context: ci/integration
          description: "Integration pipeline failed"

  pr-success:
    executor: executor_with_curl
    environment:
      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
      DEBUG: true
    steps:
      - run:
          name: pre-check for params
          command: |
            if [  "x" == "x${CYPRESS_baseUrl}"  ] ;  then
              circleci step halt # does nothing
              circleci-agent step halt # does nothing

              echo "   No parameters -skipping build ..."
              exit 0
            fi
      - github-status/post_status:
          context: e2e/cypress-test
          description: success
          state: success

  install_and_cache:
    docker:
      - image: cypress/base:24.0.0
    resource_class: lowsky/selfhosted
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
      - run:
          name: smoketest - yarn install
          command: |
            cd smoketest
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - save_cache:
          key: cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/node_modules
  test:
    docker:
      - image: cypress/base:24.0.0
    resource_class: lowsky/selfhosted
    environment:
      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
      EXPECTED_GIT_SHA: << pipeline.parameters.deployed-sha >>
      CYPRESS_branch: ${CIRCLE_BRANCH}
    steps:
      - run:
          name: Check if parameters for PR-run exist
          command: |
            echo CYPRESS_baseUrl: $CYPRESS_baseUrl
      - run:
          name: pre-check for params
          command: |
            if [  "x" == "x${CYPRESS_baseUrl}"  ] ;  then
              circleci step halt # does nothing
              circleci-agent step halt # does nothing
              echo "   No parameters -skipping build ..."
              echo "   No parameters - mark build as failed, even when there was already a good run ..."
              exit 1
            fi

      - checkout
      - run:
          name: check matching of versions
          command: |
            cd smoketest

            echo export  CYPRESS_baseUrl=$CYPRESS_baseUrl
            echo
            echo _DEBUG:  circle.ci -
            echo        CIRCLE_SHA1=$CIRCLE_SHA1
            echo _DEBUG:
            echo _DEBUG:  expecting
            echo export EXPECTED_GIT_SHA=$EXPECTED_GIT_SHA
            echo export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}
            echo _DEBUG:
            echo _DEBUG:  running
            echo      check-deployed-version/check-deployed-version

            export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}
            check-deployed-version/check-deployed-version || CHECK_VERSION=$?

            echo _  Result:  $CHECK_VERSION

            if [  "x-$CHECK_VERSION" == "x-255"  ] ;  then
              echo "Version does not match with $EXPECTED_GIT_SHA"
              exit -1
            fi

      - restore_cache:
          keys:
            - cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}

      - run:
          name: smoketest - yarn install cypress
          command: |
            cd smoketest
            yarn install --immutable
            yarn cypress install
      - save_cache:
          key: cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/node_modules

      - run:
          name: run cypress
          command: |
            cd smoketest
            mkdir -p cypress/results

            echo _DEBUG:  running without reporting to cypress.io:
            echo   CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record --key $CYPRESS_API_KEY --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            echo   CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            echo ...without reporting to cypress.io:

            CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true

      - store_test_results:
          path: smoketest/cypress/results
      - store_artifacts:
          path: /root/project/smoketest/cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: /root/project/smoketest/cypress/videos
          destination: videos
