version: 2.1
orbs:
  github-status: assurance-maladie-digital/github-status@1.3.0

parameters:
  test-url:
    type: string
    default: ''
  deployed-sha:
    type: string
    default: ''

commands:
  halt-if-no-test-url:
    steps:
      - run:
          name: Skip if no test-url parameter
          command: |
            if [ -z "${CYPRESS_baseUrl}" ]; then
              echo "No test-url parameter — skipping."
              exit 1
            fi

workflows:
  all:
    when:
      and:
        - equal: [api, << pipeline.trigger_source >>]
        - not:
            equal: ['', << pipeline.parameters.test-url >>]
    jobs:
      - pr-pending
      - test:
          requires:
            - pr-pending
      - pr-success:
          requires:
            - test

executors:
  github-status-executor:
    docker:
      - image: cimg/base:stable@sha256:35e5e29930ab565475a4f2aa9b4124998ed67dbc7b0e2dd5f420a4189d08d0d2
  cypress-executor:
    docker:
      - image: cypress/base:26.0.0@sha256:446be8fcb63e3cad2f9a4e14720e3d8e35993e12f36da541e09f5740a4c2477c
    resource_class: lowsky/selfhosted

jobs:
  pr-pending:
    executor: github-status-executor
    steps:
      - run: echo "export TARGET_URL=$CIRCLE_BUILD_URL" >> $BASH_ENV
      - github-status/pending:
          description: pending
          context: e2e/cypress-test
  pr-success:
    executor: github-status-executor
    environment:
      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
    steps:
      - halt-if-no-test-url
      - github-status/post_status:
          context: e2e/cypress-test
          description: success
          state: success

  test:
    executor: cypress-executor
    environment:
      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
      EXPECTED_GIT_SHA: << pipeline.parameters.deployed-sha >>
    steps:
      - halt-if-no-test-url
      - checkout
      - run:
          name: check matching of versions
          command: |
            cd smoketest
            export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}
            check-deployed-version/check-deployed-version || CHECK_VERSION=$?
            if [ "x-$CHECK_VERSION" == "x-255" ]; then
              echo "Version does not match with $EXPECTED_GIT_SHA"
              exit 1
            fi

      - restore_cache:
          keys:
            - cache-smoketest-v1-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}

      - run:
          name: smoketest - yarn install cypress
          command: |
            cd smoketest
            yarn install --immutable
            yarn cypress install
      - save_cache:
          key: cache-smoketest-v1-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/node_modules
            - /root/.cache/Cypress

      - run:
          name: run cypress
          command: |
            cd smoketest
            mkdir -p cypress/results

            yarn cypress info

            CYPRESS_branch=${CIRCLE_BRANCH} yarn run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true \
              -x VERCEL_AUTOMATION_BYPASS_SECRET=$VERCEL_AUTOMATION_BYPASS_SECRET,PASSWORD=$PASSWORD,PRODUCTION_PASSWORD=$PRODUCTION_PASSWORD,BRANCH=$BRANCH \
              --record --key ${CYPRESS_RECORD_KEY}

      - store_test_results:
          path: smoketest/cypress/results
      - store_artifacts:
          path: /root/project/smoketest/cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: /root/project/smoketest/cypress/videos
          destination: videos
