version: 2.1

parameters:
  test-url:
    type: string
    default: ''
  deployed-sha:
    type: string
    default: ''

# have a filter to disable regular builds.
workflows:
  all:
    jobs:
      #- install_and_cache
      - test

jobs:
  install_and_cache:
    docker:
      - image: cypress/base:20.11.0
    resource_class: lowsky/selfhosted
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
      - run:
          name: smoketest - yarn install
          command: |
            cd smoketest
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - save_cache:
          key: cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/node_modules
  test:
    docker:
      - image: cypress/base:20.11.0
    resource_class: lowsky/selfhosted
    steps:
      - run:
          name: Use parameters
          command: |
            echo parameters:
            echo test-url: << pipeline.parameters.test-url >>
            echo deployed-sha: <<pipeline.parameters.deployed-sha>>
      - run:
          name: pre-check for params
          command: |
            TEST_URL=<< pipeline.parameters.test-url >>
            if [  "x" == "x${TEST_URL}"  ] ;  then
              echo "No parameters -skipping build ..."
              exit -1
            fi
      - checkout
      - run:
          name: Use parameters
          command: |
            echo parameters:
            echo test-url: << pipeline.parameters.test-url >>
            echo deployed-sha: <<pipeline.parameters.deployed-sha>>
      - run:
          name: build env and parameter diagnosis
          command: |
            env | grep CIRCLE | sort

            CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>

      - run:
          name: check matching of versions
          command: |
            cd smoketest

            export CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            export EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>

            echo export CYPRESS_baseUrl=$CYPRESS_baseUrl
            echo
            echo _DEBUG:  circle.ci -
            echo _DEBUG:    CIRCLE_SHA1=$CIRCLE_SHA1
            echo _DEBUG:
            echo _DEBUG:  expecting
            echo export EXPECTED_GIT_SHA=$EXPECTED_GIT_SHA
            echo export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}
            echo _DEBUG:
            echo _DEBUG:  running
            echo _DEBUG:     check-deployed-version/check-deployed-version

            export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}

            check-deployed-version/check-deployed-version || CHECK_VERSION=$?

            echo _DEBUG: check - result: $CHECK_VERSION

            if [  "x-$CHECK_VERSION" == "x-255"  ] ;  then
              echo "Version does not match with $EXPECTED_GIT_SHA"
              exit -1
            fi

      - restore_cache:
          keys:
            - cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
      - run:
          name: smoketest - yarn install
          command: |
            cd smoketest
            yarn install --immutable --check-cache
            yarn cypress cache path
            yarn cypress install
            yarn cypress verify
      - save_cache:
          key: cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
          paths:
            - smoketest/node_modules

      - run:
          name: run cypress
          command: |
            export CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
            export EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>
            export CYPRESS_branch=${CIRCLE_BRANCH}

            cd smoketest
            mkdir -p cypress/results
            yarn dlx cypress info

            echo _DEBUG:  running CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record
            # CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record --key $CYPRESS_API_KEY --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            # CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
            # without reporting to cypress.io
            CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
      - store_test_results:
          path: smoketest/cypress/results
      - store_artifacts:
          path: /root/project/smoketest/cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: /root/project/smoketest/cypress/videos
          destination: videos
